
package visao;

import modeloConection.ConexaoBD;

public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    public TelaPrincipal(String usuario) {
        initComponents();
        jLabelUsuarioLogado.setText(usuario);
        conecta.conexao();
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemvindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadProfessores = new javax.swing.JButton();
        jButtonCadUsuarios = new javax.swing.JButton();
        jButtonCadAlunos = new javax.swing.JButton();
        jButtonCadModalidade = new javax.swing.JButton();
        jButtonCadTurma = new javax.swing.JButton();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFecharBemvindo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelUsuarioLogado = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadProfessores = new javax.swing.JMenuItem();
        jMenuItemCadAlunos = new javax.swing.JMenuItem();
        jMenuItemCadModalidade = new javax.swing.JMenuItem();
        jMenuItemCadTurma = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenuMatricular = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemvindo = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemvindo.setTitle("Bem-Vindo");
        jInternalFrameBemvindo.setVisible(true);
        jInternalFrameBemvindo.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelInternal.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastros - ");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(30, 20, 140, 14);

        jButtonCadProfessores.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadProfessores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadProfessores.setForeground(new java.awt.Color(0, 0, 51));
        jButtonCadProfessores.setText("Professores");
        jButtonCadProfessores.setToolTipText("Cadastro de Professor");
        jButtonCadProfessores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCadProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadProfessoresActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadProfessores);
        jButtonCadProfessores.setBounds(480, 50, 90, 40);

        jButtonCadUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadUsuarios.setForeground(new java.awt.Color(0, 0, 51));
        jButtonCadUsuarios.setText("Usuários");
        jButtonCadUsuarios.setToolTipText("Cadastro de Usuário");
        jButtonCadUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuariosActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadUsuarios);
        jButtonCadUsuarios.setBounds(30, 50, 90, 40);

        jButtonCadAlunos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadAlunos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadAlunos.setForeground(new java.awt.Color(0, 0, 51));
        jButtonCadAlunos.setText("Alunos");
        jButtonCadAlunos.setToolTipText("Cadastro de Aluno");
        jButtonCadAlunos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCadAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadAlunosActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadAlunos);
        jButtonCadAlunos.setBounds(140, 50, 80, 40);

        jButtonCadModalidade.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadModalidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadModalidade.setForeground(new java.awt.Color(0, 0, 51));
        jButtonCadModalidade.setText("Modalidade");
        jButtonCadModalidade.setToolTipText("Cadastro de Modalidade");
        jButtonCadModalidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCadModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadModalidadeActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadModalidade);
        jButtonCadModalidade.setBounds(240, 50, 100, 40);

        jButtonCadTurma.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadTurma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadTurma.setForeground(new java.awt.Color(0, 0, 51));
        jButtonCadTurma.setText("Turma");
        jButtonCadTurma.setToolTipText("Cadastro de Turma");
        jButtonCadTurma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadTurmaActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadTurma);
        jButtonCadTurma.setBounds(370, 50, 80, 40);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTelaPrincipalPainelInterno.jpg"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(10, 10, 680, 230);

        jInternalFrameBemvindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(10, 30, 700, 250);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jInternalFrameBemvindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 290, 22);

        jButtonFecharBemvindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão-fechar.png"))); // NOI18N
        jButtonFecharBemvindo.setToolTipText("Fechar Tela Bem-Vindo");
        jButtonFecharBemvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBemvindoActionPerformed(evt);
            }
        });
        jInternalFrameBemvindo.getContentPane().add(jButtonFecharBemvindo);
        jButtonFecharBemvindo.setBounds(660, 0, 20, 20);

        getContentPane().add(jInternalFrameBemvindo);
        jInternalFrameBemvindo.setBounds(10, 50, 700, 310);

        jLabel3.setText("Usuário:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 370, 60, 20);

        jLabelUsuarioLogado.setBackground(new java.awt.Color(102, 102, 102));
        jLabelUsuarioLogado.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuarioLogado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelUsuarioLogado);
        jLabelUsuarioLogado.setBounds(580, 370, 140, 20);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoTelaPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, -220, 860, 860);

        jMenuCadastros.setText("Cadastros");

        jMenuItemCadProfessores.setText("Cadastro Professores ");
        jMenuItemCadProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadProfessoresActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadProfessores);

        jMenuItemCadAlunos.setText("Cadastro Alunos");
        jMenuItemCadAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadAlunosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadAlunos);

        jMenuItemCadModalidade.setText("Cadastro Modalidade");
        jMenuItemCadModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadModalidadeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadModalidade);

        jMenuItemCadTurma.setText("Cadastro Turma");
        jMenuItemCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadTurmaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadTurma);

        jMenuItemCadUsuarios.setText("Cadastro Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadUsuarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuMatricular.setText("Matricular");
        jMenuBar1.add(jMenuMatricular);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemvindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemvindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemvindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(747, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadModalidadeActionPerformed
        FormModalidade tela = new FormModalidade();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadModalidadeActionPerformed

    private void jMenuItemCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadTurmaActionPerformed
        FormTurma tela = new FormTurma();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadTurmaActionPerformed

    private void jButtonCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuariosActionPerformed
        FormUsuario tela = new FormUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadUsuariosActionPerformed

    private void jButtonCadProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadProfessoresActionPerformed
        FormProfessor tela = new FormProfessor();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadProfessoresActionPerformed

    private void jButtonCadAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadAlunosActionPerformed
        FormAluno tela = new FormAluno();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadAlunosActionPerformed

    private void jButtonCadModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadModalidadeActionPerformed
        FormModalidade tela = new FormModalidade();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadModalidadeActionPerformed

    private void jButtonCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadTurmaActionPerformed
        FormTurma tela = new FormTurma();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadTurmaActionPerformed

    private void jButtonFecharBemvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBemvindoActionPerformed
        jInternalFrameBemvindo.dispose();
    }//GEN-LAST:event_jButtonFecharBemvindoActionPerformed

    private void jMenuItemTelaBemvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemvindoActionPerformed
//        TelaPrincipal tela = new TelaPrincipal();
//        tela.setVisible(true);
//        dispose();
        jInternalFrameBemvindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaBemvindoActionPerformed

    private void jMenuItemCadProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadProfessoresActionPerformed
        FormProfessor tela = new FormProfessor();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadProfessoresActionPerformed

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
        FormUsuario tela = new FormUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemCadAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadAlunosActionPerformed
        FormUsuario tela = new FormUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadAlunosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadAlunos;
    private javax.swing.JButton jButtonCadModalidade;
    private javax.swing.JButton jButtonCadProfessores;
    private javax.swing.JButton jButtonCadTurma;
    private javax.swing.JButton jButtonCadUsuarios;
    private javax.swing.JButton jButtonFecharBemvindo;
    private javax.swing.JInternalFrame jInternalFrameBemvindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuarioLogado;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadAlunos;
    private javax.swing.JMenuItem jMenuItemCadModalidade;
    private javax.swing.JMenuItem jMenuItemCadProfessores;
    private javax.swing.JMenuItem jMenuItemCadTurma;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemTelaBemvindo;
    private javax.swing.JMenu jMenuMatricular;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
